##h2
#    spring.application.name=e-shop-backend
#
#    springdoc.api-docs.enabled=true
#    springdoc.swagger-ui.enabled=true
#
#    spring.datasource.url=jdbc:h2:mem:emc-2026
#    spring.datasource.username=emc
#    spring.datasource.password=emc
#    spring.jpa.hibernate.ddl-auto=create-drop
#

spring.datasource.url=jdbc:postgresql://localhost:5433/eshop
spring.datasource.username=emc
spring.datasource.password=emc

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
