#spring.application.name=e-shop-backend
#
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#logging.level.root=INFO
#logging.level.mk.ukim.finki.eshopbackend=DEBUG
#logging.level.org.springframework=WARN
#
#logging.file.name=logs/app.log
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.max-history=30
#
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
#
#
#
#spring.profiles.active=dev
#spring.h2.console.enabled=false
spring.application.name=e-shop-backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.mk.ukim.finki.eshopbackend=DEBUG
logging.level.org.springframework=WARN

logging.file.name=logs/app.log  
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

#lab3
#jwt.secret=${JWT_SECRET_KEY}
jwt.secret=7ac51f34954d17b2c22a1a95ea44f1f61c72a0b87d186c8e2c607edb4db99ffd
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

spring.profiles.active=dev